### ISSUE TITLE
Tutorial notebooks

### ISSUE THREAD

**Issue by Buffoni** [qutip/qutip-qip#143]
Hi @BoxiLi @nathanshammah, I'm interested in contributing to this package as I applied for a project for GSoC '22.
I think it could be good to implement some tutorial notebooks to showcase some functionalities of qutip-qip in a user-friendly way. Do you think it could be a good idea?

**Comment by BoxiLi** [comment]
Hi @Buffoni, there are a few qip-related notebooks available on https://qutip.org/tutorials.html. You are very welcome to improve upon them or add any new ones!

**Comment by BoxiLi** [comment]
I'm closing this as it is general and we don't have any specific tasks at the moment. Contributions to notebooks are always welcome!
