### ISSUE TITLE
Add tests for the circuit plotting

### ISSUE THREAD

**Issue by BoxiLi** [qutip/qutip-qip#178]
Install texlive and the circuit plotting dependencies in one of the test actions and add a few tests.

**Comment by BoxiLi** [comment]
Examples can be found in https://github.com/qutip/qutip-tutorials/blob/main/.github/workflows/notebook_ci.yaml

**Comment by Anika-Roy** [comment]
Hello! is this open?

**Comment by BoxiLi** [comment]
Hi, yes this is still open. You are welcome to contribute!

**Comment by Anika-Roy** [comment]
Could you assign it to me please? 
Also, I'm new to open source, could you guide me a little on how to get started?

**Comment by Anika-Roy** [comment]
Could you tell me what circuit plotting tests are you looking for? A related issue mentioned SWAP gate i think.

**Comment by BoxiLi** [comment]
Hi, @Anika-Roy sorry for the delay. And thank you for your interest!

The main goal is to run one or a few circuit plotting tasks during the test action so that if something goes wrong, errors will be detected. There is no way to check if the plotted circuit is exactly what we want. But this will at least get our attention when an error is raised.

We don't have a default circuit to test against. But you can find a few examples in the documentation. Ideally the test should cover as many types of gates (and some measurements) as possible. The circuit itself does not to have any meaning.

You can find a guide on how to contribute in the doc. Please let me know if you have more questions!

**Comment by Anika-Roy** [comment]
Thank you for replying! 
I'll start working on it and let you know when I have some doubts.

**Comment by Anika-Roy** [comment]
Is the circuit plotting feature only for Jupyter notebook?
I was trying to run some sample code in the documentation from a .py file and it keeps giving me this error,
Traceback (most recent call last):
  File "/home/anika/Desktop/qutip/test.py", line 19, in <module>
    pic.png
  File "/home/anika/miniconda3/envs/qutip/lib/python3.10/site-packages/qutip_qip/circuit.py", line 2009, in png
    return DisplayImage(self._repr_png_(), embed=True)
AttributeError: 'QubitCircuit' object has no attribute '_repr_png_'
Would you recommend I work on Jupyter notebooks instead?

**Comment by BoxiLi** [comment]
It is designed for the notebook but should also work in an ipython console or pure python.

But your error looks independent on that. Have you installed LaTeX and the other external packages? And are you using `import qutip_qip` or `import qutip.qip`?

You can have a look at the installation guide in the documentation. There are a few additional softwares that needs to be installed for the plotting.

**Comment by Anika-Roy** [comment]
Got it, 
thank you

**Comment by Anika-Roy** [comment]
I installed all the dependencies to the best of my knowledge and I'm getting a new error this time. Could you help me out?

RuntimeError: convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.
convert-im6.q16: no images defined `qcirc.png' @ error/convert.c/ConvertImageCommand/3258.

**Comment by Anika-Roy** [comment]
I'm facing trouble with running circuit plots. 
The documentation handled the error:
"RuntimeError: convert-im6.q16: not authorized `qcirc.pdf' @ error/constitute.c/ReadImage/412.
convert-im6.q16: no images defined `qcirc.png' @ error/convert.c/ConvertImageCommand/3258."
I implemented the solution but I keep getting a slightly different error:
"RuntimeError: convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.
convert-im6.q16: no images defined `qcirc.png' @ error/convert.c/ConvertImageCommand/3258."

I have downloaded all the dependencies that were mentioned. Could you help me fix this?

**Comment by BoxiLi** [comment]
I have never seen this but this is certainly related to Imagemagick. May you need this instead https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion.
With `domain="coder"`.

**Comment by BoxiLi** [comment]
Close as it is addressed in the GSoC project
