### ISSUE TITLE
How can i generate the quantum circuit image with qutip? 

### ISSUE THREAD

**Issue by luopeis** [qutip/qutip-qip#197]
Dear Respected Members of the Group,

I am trying to generate the quantum circuit with qutip,following the qutip document

[https://nbviewer.org/urls/qutip.org/qutip-tutorials/tutorials-v4/quantum-circuits/quantum-gates.ipynb](url)
The doucument said we need four packages to achieve generating the quantum circuit image.
![asdhajkshd](https://user-images.githubusercontent.com/128964528/230728241-43bbc2bf-03f4-4c65-9414-1a4c24c179e2.png)

But I am sure about I definitly did  `pip install pdflatex`,and I can find "pdflatex" in my folder.But when I want to find "pdflatex" in Command(cmd), using `where pdflatex`, some troubles happend.

![sada](https://user-images.githubusercontent.com/128964528/230728497-9730d705-fc19-4584-b90e-fc86f7193089.png)
 

 The chinese of the above picture means:   INFO: Could not find the file with the provided pattern.

My computer system is windows 11,and already has installed  Imagemagick, perl, Ghostscript ,latex and pdflatex

I kindly ask for your help with many many thanks in advance.
Thank you from the bottom of my deep heart
 Yours sincerely.

**Comment by hodgestar** [comment]
You can try following the instructions at
https://github.com/hodgestar/qutip-asqsqis-2022#windows for installing the
necessary software for rendering the circuit diagrams.

If pdflatex is not found on the command line it likely means that QuTiP
won't find it either.

Relying on LaTeX to render circuit diagrams is fragile and complex. We hope
to add options for rendering circuits with matplotlib and text in the
coming months.

Regards,
Simon

**Comment by luopeis** [comment]
Thanks my dear friend @hodgestar ,
It very helpful to me, I have successfully installed `perl.exeI`and  `ImageMagick`
I follow [https://github.com/hodgestar/qutip-asqsqis-2022#windows](url) step by step, but there was some new error.

![first](https://user-images.githubusercontent.com/128964528/230753448-82a956e
![second](https://user-images.githubusercontent.com/128964528/230753461-32bb2c9d-04f1-486c-acc6-cade6c804740.png)
8-dc3f-4a2b-9142-cb8db395fa58.png)

Anyway, if there are other solutions. I would be appreciate it.
Thank you very much for your help.
Yours sincerely,

**Comment by hodgestar** [comment]
@luopeis As the error says, the output from ImageMagick isn't in the encoding Python expects. You will need to fix that but it doesn't seem to be an issue with qutip-qip, more with how your system is configured.

Calling Python with `PYTHONIOENCODING=utf-8:surrogateescape python3` or similar might help, but this is not really something I can help fix. You'll have to figure it out yourself.

**Comment by luopeis** [comment]
@hodgestar I have solved the problem, successfully generate the quantum circuit. Thank you for your help.  Allow me to show you my respect for you. My problem is that I mistake the software for package in python.

[[https://nbviewer.org/urls/qutip.org/qutip-tutorials/tutorials-v4/quantum-circuits/qip-toffoli-cnot.ipynb](https://github.com/qutip/qutip-qip/issues/url)](url)

Here is my question.  The red part `conda install magemagick` in below picture make  me regard the `latex` `imagemagick`  `perl` and`ghostscript` as  the package in python. Actually the four thing is software which you must go to thire website to download.

![图示](https://user-images.githubusercontent.com/128964528/230768362-7f6faa31-84e7-42f8-8d82-50f58b65a789.png)

Here is some my advice for Windows users：

> Latex:  you can go to  [https://www.latex-project.org/get/](url) to download "MikTeX"

> ImageMagick:：  go  to  [https://imagemagick.org/script/download.php](url) . To install ImageMagick, you need to download Visual C++ Redistributable Package,which is also provided in [https://imagemagick.org/script/download.php](url).

>Perl: [https://strawberryperl.com/](url)

> GhostScript:  [https://www.ghostscript.com/releases/gsdnld.html](url)


Don't mistake the software with the package in python.  Becaues if you want to `pip install latex` `pip install perl` `pip install ghostscript`,the commend will give you a successful result.

**Comment by hodgestar** [comment]
@luopeis Thanks for the update an the suggestion for others. Glad you got circuits working!
