### ISSUE TITLE
Add qutip-qip tutorials to documentation on Read the docs 

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-qip#204]
# Issue description
Add links for exisiting qutip-qip notebooks on the read the docs documentation at https://qutip-qip.readthedocs.io/en/stable/, similarly to what is done for Mitiq. Right now there is a tutorials section (see screenshot below) 

<img width="905" alt="qutipqip-doc" src="https://github.com/qutip/qutip-qip/assets/14573436/67802315-f5c9-4860-8a27-f296154e8500">

but it only contains a link to qutip.org, as the tutorials appear only on the https://qutip.org/qutip-tutorials/ under the QIP section, see screenshot below.

<img width="464" alt="qutip-qip" src="https://github.com/qutip/qutip-qip/assets/14573436/ce01589a-18ea-4d98-9c76-f96c8cfed078">

# Proposed Solution
The tricky part is that we don't want to duplicate the files, the source files should remain from `qutip-tutorials`, such as for the
"[Decomposition of the Toffoli gate in terms of CNOT and single-qubit rotations](https://nbviewer.org/urls/qutip.org/qutip-tutorials/tutorials-v4/quantum-circuits/qip-toffoli-cnot.ipynb)" that is rendered from
```
https://nbviewer.org/urls/qutip.org/qutip-tutorials/tutorials-v4/quantum-circuits/qip-toffoli-cnot.ipynb
```   
The tutorials should be kept also on the https://qutip.org/qutip-tutorials/#quantum-information-processing as they currently exist. 

# References
- https://qutip-qip.readthedocs.io/en/stable/
- https://qutip.org/qutip-tutorials/#quantum-information-processing
- https://github.com/qutip/qutip-tutorials

**Comment by Algh89110377** [comment]
Hi, It is my first time contributing to open-source problems. I like to tackle this one. Will you please add me?

**Comment by natestemen** [comment]
Hackers! This bounty has increased in value! What was worth $50 is now $100!

**Comment by miaortizma** [comment]
Hi, would git submodules be an acceptable solution?

**Comment by BoxiLi** [comment]
@rum Could you comment here so that I can assign you?

**Comment by rum1887** [comment]
Hi,  here's the pr for this issue #207

**Comment by BoxiLi** [comment]
@nathanshammah @natestemen This has been solved! Thank you @rum1887

**Comment by rum1887** [comment]
> @nathanshammah @natestemen This has been solved! Thank you @rum1887 

Awesome
Thanks @BoxiLi for being patient and answering all the doubts :)

**Comment by nathanshammah** [comment]
Congratulations @rum1887!
