### ISSUE TITLE
Running tests and src folder

### ISSUE THREAD

**Issue by purva-thakre** [qutip/qutip-qip#21]
Is there some preferred way to run tests locally with `src/qutip_qip` path ? I wanted to check before I made a large number of changes. 

Usually, I will navigate to the tests folder `cd qutip-project/qutip-qip/tests` and then run `pytest some_test.py`. This does appear to be the [preferred method in documentation](http://qutip.org/docs/latest/development/contributing.html#testing) except the documentation  example specifies the directory for pytest exactly whereas I navigate to `tests` folder (as stated above). I have found two different methods to make sure modules are imported properly. I have used first one successfully and others are some options not yet tried (but do seem reasonable). 

1. Just add `src` to the module's path. 

``` python
from src.qutip_qip.qasm import read_qasm
```
2. Specify PYTHONPATH manually in file of `some_test.py` or let Python handle PYTHONPATH

```python
python pytest tests/some_test.py
```

**Comment by BoxiLi** [comment]
Hi @purva-thakre 

Maybe miss the key point of your question, please point out if I do. 

If you are using conda install `qutip_qip` in an editable way by
```
pip install -e  .
```
in this environment. Then running `pytest`  under tests folder *is* testing the local file under `src/qutip_qip/qasm...`. In principle, there should be no need to manipulate the module path. Or maybe I missed the reason in your case?

In some sense, the `src` structure is to prevent accidentally importing from not-installed files. See https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure

**Comment by purva-thakre** [comment]
@BoxiLi Yes, I do have the editable version installed. 

You didn't miss the key point of my question except for the module path. I change directory to `src/qutip_qip/tests` and then run 
`pytest some_test.py`. 

Let `some_test` import some `qip` module. If it is imported as `from qutip_qip import something` then I kept on getting an error that module `qutip_qip` does not exist unless I change it to `from src.qutip_qip import something`.  So, before I changed all imports in a similar manner, I wanted to verify if this change was needed or not. I felt that it was not needed since checks on currently open PR's passed without specifying PYTHONPATH or adding on `src.` before `qutip_qip` in a workflow job. 

I think I am going to create a new virtual environment and re-install things. I messed with PYTHONPATH way too many times in my current environment ! Hopefully, this will turn out to be the culprit.

**Comment by BoxiLi** [comment]
> If it is imported as from qutip_qip import something then I kept on getting an error that module qutip_qip does not exist unless I change it to from `src.qutip_qip import` something.

That does sound like `qutip_qip` was not correctly installed. The importation should be `from qutip_qip import something`, without `src`.

One possible reason: did you check if qutip_qip is installed under your current environment? For instance, if you start from a fresh conda and use pip install, there is no python or pip in that environment. And the system may just use the system default pip.

**Comment by purva-thakre** [comment]
Yes, I did have it installed in the correct environment. A new environment and a fresh install of qutip worked. Thanks !
