### ISSUE TITLE
Processor run_state is not reproducible due to accumulation of noise channel

### ISSUE THREAD

**Issue by andgoldschmidt** [qutip/qutip-qip#230]
There is an after effect to running a simulation. I would expect processors to be reusable and simulations to be repeatable.

Set up a processor for aT1 simulation.
```Python
processor = Processor(1, t1=t1, t2=None)
processor.add_pulse(Pulse(None, None, tlist=t_eval, coeff=False))
print(processor.noise)
```
```
[]
```

Run the processor.
```Python
a = qt.destroy(2)
psi0 = qt.basis(2,1)
result = processor.run_state(init_state=psi0, e_ops=[a.dag()*a])
print(processor.noise)
```
```
<qutip.qip.noise.RelaxationNoise object...>
```

Now, the next simulation has double the decoherence processes.

The after effect is noted in the docstring of _processor.py_
```Python
    def get_noisy_pulses(self, device_noise=False, drift=False):
        """
        It takes the pulses defined in the `Processor` and
        adds noise according to `Processor.noise`. It does not modify the
        pulses saved in `Processor.pulses` but returns a new list.
        The length of the new list of noisy pulses might be longer
        because of drift Hamiltonian and device noise. They will be
        added to the end of the pulses list.
...
```
due to calling
```Python
    noisy_pulses = process_noise(
        pulses, self.noise, self.dims, t1=self.t1, t2=self.t2,
        device_noise=device_noise)
```
instead of 
```Python
    noisy_pulses = process_noise(
        pulses, deepcopy(self.noise), self.dims, t1=self.t1, t2=self.t2,
        device_noise=device_noise)
```
or modifying the `process_noise` not to add noise channels to the processor. Is there a reason why there is an append to self.noise inside process_noise?

**Comment by BoxiLi** [comment]
Thanks for the issue.

Yes, this was a bug. `process_noise` should not change the list of noise channels in the processor. This should be fixed in https://github.com/qutip/qutip-qip/pull/89 already, seeing the change in  https://github.com/qutip/qutip-qip/pull/89/files. It is similar to what you did. It should be included in `qutip-qip>=0.1.2`
