### ISSUE TITLE
Incorrect indexing of `qubits` in `circuit.add_1q_gate`

### ISSUE THREAD

**Issue by hatlabcz** [qutip/qutip-qip#248]
Hello,  

I noticed what appears to be a typo in the `circuit.add_1q_gate` method when applying the 1q gate to specific qubits indexed in the `qubits` list. This might cause incorrect gate applications if the code is used as-is.

Current code:
https://github.com/qutip/qutip-qip/blob/2ff56326957e6d527362734c13f97dad4a6fbacc/src/qutip_qip/circuit/circuit.py#L300-L303

Proposed Fix:
```
 if qubits is not None: 
     for q_ in qubits: 
         gate = GATE_CLASS_MAP[name]( 
             targets=q_, 
```

**Comment by BoxiLi** [comment]
Thank you for the issue! Bug fixed.
