### ISSUE TITLE
Warning on gates when running basic code block from documentation

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-qip#32]
I created a fresh conda environment with python==3.8 and run
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.python.org/simple/ qutip-qip
It installed qutip-qip very fast. Do we have some sort of qutip.about() for qutip.qip? Or some basic test to test the installation?

I ran the code blocks at 
and all worked fine. I got the following Warning when plotting the circuit: https://qutip-qip.readthedocs.io/en/latest/qip-basics.html

```
/opt/miniconda3/envs/qutip-qip/lib/python3.8/site-packages/qutip_qip/circuit.py:274: UserWarning: Unknown gate H
  warnings.warn("Unknown gate %s" % name)
```

**Comment by BoxiLi** [comment]
No, we don't yet have something like `qutip.about()`. Maybe I can import that qutip module and use it.

In qutip-qip the `tests` folder is not packed in the installed version, because it is not in `src`. So I don't think there is a way to do something like `qutip.testings.run()`. The only way to test the code is to download the tests code and run pytest in that folder I think. Maybe @hodgestar knows something about this?

**Comment by BoxiLi** [comment]
About `qutip.about()` I think the easiest way is to modify the `qutip.about()` function, try to find if `qutip-qip` is installed and  display it if it is installed.

**Comment by hodgestar** [comment]
> In qutip-qip the `tests` folder is not packed in the installed version, because it is not in `src`. So I don't think there is a way to do something like `qutip.testings.run()`. The only way to test the code is to download the tests code and run pytest in that folder I think. Maybe @hodgestar knows something about this?

Generally I think keeping the test files outside the package is a good idea (it make the separation between the two very clear & keeps the size of the installed package down). If they're separate then there isn't a good way to run the tests without the source package. I think that's fine -- the time to run the tests is when the wheels are built, I think (i.e. in our GitHub deploy action).

**Comment by BoxiLi** [comment]
This should have already been fixed long ago.
