### ISSUE TITLE
Add information on the qutip-qip pulse paper

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-qip#55]
We should add information on the preprint of the paper introducing the pulse features in `qutip-qip`. 
My suggestion is to add:
- [  ] 1. a badge with the arXiv link in the readme, next to the other shields. Similarly to what done [here](https://github.com/unitaryfund/mitiq/).
- [  ] 2. A "Cite" section that shows up in the Readme
- [  ] 3. A "Cite" section that shows up in the documentation
- [  ] 4. Similarly to what done in QuTiP, include a `.bib` bibliography file somewhere in the documentation, and also have the snippet show up in the docs, for easy copy-paste, as done [here](https://mitiq.readthedocs.io/en/stable/research.html#citing-mitiq).

**Comment by purva-thakre** [comment]
I can take this. 

> A "Cite" section that shows up in the documentation

Do you prefer a separate link at the left or add this information to the introduction page ?
