### ISSUE TITLE
Adding a link in RTD to fork the repo

### ISSUE THREAD

**Issue by purva-thakre** [qutip/qutip-qip#57]
Which of the following styles are preferred to link to the main repo : [style 1](https://github.blog/2008-12-19-github-ribbons/), [style 2](https://tholman.com/github-corners/) ?

I know that in the past @nathanshammah has preferred to have style 2 because style 1 looks a bit old. Personally, I like both.

Right now each page in the documentation has a link to the source file to be able to make changes directly. It would be good to also have a link to the main repo accessible either to the top right or left or some other position.

**Comment by nathanshammah** [comment]
Thanks @purva-thakre. We could use the right ribbon, maybe of a different color, for consistency with the one in https://qutip.org/documentation.html.
