### ISSUE TITLE
How can i generate the quantum circuit image with qutip?

### ISSUE THREAD

**Issue by FarooqKhaleel** [qutip/qutip-qip#64]
Dear Respected Members of the Group,
I hope you are doing well.
I am trying to reproduce the results of the following post:

https://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/examples/quantum-gates.ipynb#Gates-in-QuTiP-and-their-representation

in windows 10 environment and with Imagemagick, perl, Ghostscript and Latex are all installed and verified.
However, it seems like it cant generate the qcirc.pdf file. I receive the following error,

Warning (from warnings module):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 128
    warnings.warn("Could not locate system 'pdfcrop':"
UserWarning: Could not locate system 'pdfcrop': image output may have additional margins.
Traceback (most recent call last):
  File "C:\Users\msi-pc\Desktop\farrrrr.py", line 11, in <module>
    q.png
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit.py", line 1821, in png
    return DisplayImage(self._raw_png(), embed=True)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit.py", line 1811, in _raw_png
    return _latex.image_from_latex(self.latex_code(), "png")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 245, in image_from_latex
    out = CONVERTERS[file_type](filename)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 180, in converter
    _run_command((which, *configuration.arguments, in_file, out_file))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 65, in _run_command
    raise RuntimeError(e.stderr.decode(sys.stderr.encoding)) from None
RuntimeError: magick: unable to open image 'qcirc.pdf': No such file or directory @ error/blob.c/OpenBlob/3537.

I kindly ask for your help with many thanks in advance.
Thank you very much
Yours sincerely,

**Comment by purva-thakre** [comment]
> UserWarning: Could not locate system 'pdfcrop': image output may have additional margins

You need to install `pdfcrop`. It could be solved by installing[ `texlive-extra-utils`](https://askubuntu.com/questions/864474/how-to-install-pdfcrop-in-ubuntu-14-04) or one of the recommended prerequisites for [latextools](https://pypi.org/project/latextools/). 

@BoxiLi This seems to be a Windows issue.

**Comment by FarooqKhaleel** [comment]
Is there a pip command for texlive-extra-utils tool?

**Comment by FarooqKhaleel** [comment]
I installed the Latextool by the pip command, and i get the issue. 
I am looking forward for other solutions.
Thank you very much for your help

**Comment by purva-thakre** [comment]
@FarooqKhaleel You need not install `latextools`. 

I meant the prerequisites for `latextools` which are listed on the [linked webpage](https://pypi.org/project/latextools/) - `texlive-latex-recommended texlive-latex-extra`.

**Comment by FarooqKhaleel** [comment]
@purva-thakre 
Thank you very much for your answer.
I tried and didnt work.
They couldnt be installed using pip commands.
I am running on windows 10 64 bits.
All other wheels that are required to be installed such magick, perl , etc. Are installed and verified.
I am lookong forward for your help.
Thanks alot

**Comment by BoxiLi** [comment]
Hi @FarooqKhaleel , may I ask how you installed the LaTeX distribution? QuTiP's plotting functionality relies on the `qcircuit` package of LaTeX and it could be that you only installed the core latex without any packages. 

On windows, I would recommend using MikTeX, which automatically install new packages if it is required. It takes a few extra minutes on the first run, but solves the trouble.

**Comment by FarooqKhaleel** [comment]
@BoxiLi Thank you very much for your answer.

Regarding the LaTeX, i installed using pip commands

pip install Latex
pip install latextools

However, your advice almost worked.
Installing MikTeX almost solved the problem. However, I get the following error. It seems that qutip can not generate the pdf file.
qcirc.pdf.



Traceback (most recent call last):
  File "C:\Users\msi-pc\Desktop\farrrrr.py", line 13, in <module>
    q.png
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit.py", line 1821, in png
    return DisplayImage(self._raw_png(), embed=True)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit.py", line 1811, in _raw_png
    return _latex.image_from_latex(self.latex_code(), "png")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 233, in image_from_latex
    _crop_pdf(filename + ".pdf")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 121, in _crop_pdf
    _run_command((_pdfcrop, filename, temporary))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 65, in _run_command
    raise RuntimeError(e.stderr.decode(sys.stderr.encoding)) from None
RuntimeError: pdfcrop: security risk: running with elevated privileges

initexmf: security risk: running with elevated privileges

initexmf: security risk: running with elevated privileges

**!!! Error: Input file `qcirc.pdf' not found!**

I am looking forward for your help.
Thank you very much for your help.
Yours sincerely,

**Comment by BoxiLi** [comment]
The packages
```
pip install Latex
pip install latextools
```
are not required. They are both Python packages that build a link between LaTeX and Python. An independent LaTeX distribution like MikTex is still required. Sorry if our installation guide is a bit vague on this.

Although the error message changes, it doesn't seem like we went very far... The `qcric.pdf` is still not generated. Have you tried to rerun the same python script? It could be that the first time MikTeX is installing new dependencies and needs to be reloaded.

The warning `security risk: running with elevated privileges` indicates that you probably installed MikTeX with in the administrator  mode, which shouldn't be a big problem I think, despite some warning.

**Comment by purva-thakre** [comment]
@FarooqKhaleel You might want to re-install MikTex as a single user instead of as an admin. [See this comment for more information. ](https://github.com/MiKTeX/miktex/issues/83#issuecomment-437970638)

**Comment by FarooqKhaleel** [comment]
Dear @BoxiLi @purva-thakre 
I hope you are doing well.
The problem is the same. The qcirc.pdf file still cant be generated. :(
I restarted my PC after re-installing miktex as a single user and I am running the following code:

from IPython.display import Image
from numpy import pi
import numpy as np
import latex
from qutip import *
from qutip_qip.operations import *
from qutip_qip.circuit import QubitCircuit, Gate
q = QubitCircuit(2, reverse_states=False)
q.add_gate("CSIGN", controls=[0], targets=[1])
q.png


I still receive the following error:
Traceback (most recent call last):
  File "C:\Users\msi-pc\Desktop\farrrrr.py", line 10, in <module>
    q.png
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit.py", line 1821, in png
    return DisplayImage(self._raw_png(), embed=True)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit.py", line 1811, in _raw_png
    return _latex.image_from_latex(self.latex_code(), "png")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 233, in image_from_latex
    _crop_pdf(filename + ".pdf")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 121, in _crop_pdf
    _run_command((_pdfcrop, filename, temporary))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 65, in _run_command
    raise RuntimeError(e.stderr.decode(sys.stderr.encoding)) from None
RuntimeError: pdfcrop: security risk: running with elevated privileges

!!! Error: Input file `qcirc.pdf' not found!



Thank you very much for your help.
Yours sincerely,

**Comment by purva-thakre** [comment]
@FarooqKhaleel 

Here's a couple of links that might be able to help : 
- https://tex.stackexchange.com/a/67713/203959
- https://tex.stackexchange.com/a/56322/203959
- https://tex.stackexchange.com/a/547190/203959

It's possible there's a clash with some packages being installed as an admin and some not. 

Have you also checked if the latest version of MikTex is installed ? After the installation, did you check for updates ?
- https://miktex.org/howto/install-miktex
- https://miktex.org/howto/miktex-console

Check if all of the needed latex dependencies are installed - `braket, qcircuit, pdfcrop, pdflatex`

**Comment by FarooqKhaleel** [comment]
Dear @purva-thakre 
Thank you for your help.
The following error stuck. I re-installed miktex and go to packages and installed all the aforementioned latex dependencies. The error is the same. :((
Maybe there is an issue with my PC.

Traceback (most recent call last):
  File "C:\Users\msi-pc\Desktop\farrrrr.py", line 10, in <module>
    q.png
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit.py", line 1821, in png
    return DisplayImage(self._raw_png(), embed=True)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit.py", line 1811, in _raw_png
    return _latex.image_from_latex(self.latex_code(), "png")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 233, in image_from_latex
    _crop_pdf(filename + ".pdf")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 121, in _crop_pdf
    _run_command((_pdfcrop, filename, temporary))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qutip_qip\circuit_latex.py", line 65, in _run_command
    raise RuntimeError(e.stderr.decode(sys.stderr.encoding)) from None
RuntimeError: pdfcrop: security risk: running with elevated privileges

!!! Error: Input file `qcirc.pdf' not found!


Anyway, if there are other solutions. I would be appreciate it.
Thank you very much for your help.
Yours sincerely,

**Comment by BoxiLi** [comment]
Ok, sorry to hear that it is still not working. The pdf is still not successfully generated. It is really hard to check the LaTeX error source from python. So if you still have hope, let's do a more thorough diagnostics from the LaTeX side.

Could you copy the following lines into a text file and name it `qcircuit_example.tex`
``` tex
\documentclass{article}
\usepackage{qcircuit}

\begin{document}
\Qcircuit @C=1em @R=.7em {
& \gate{H} & \gate{Z} & \gate{H} & \qw \\
& \qw & \gate{X} & \qw & \qw
}
\end{document}
```

It is a minimal example to plot quantum circuit using [qcircuit](https://ftp.agdsn.de/pub/mirrors/latex/dante/graphics/qcircuit/qcircuit.pdf). Then, please go to the file directory and run the command line `pdflatex qcircuit_example.tex` and see what is the output. We will probably see quite a few lines of logging info. If everything succeed, it should end with something like
```
Output written on qcircuit_example.pdf (1 page, 18859 bytes).
Transcript written on qcircuit_example.log.
```

The pdf will look like this
![image](https://user-images.githubusercontent.com/12125783/122883889-e5650200-d33d-11eb-9f0a-e905f5a75b96.png)

If something went wrong, the log information should tell.

**Comment by FarooqKhaleel** [comment]
Dear @BoxiLi 
I hope you are doing well and thank you very much for your help and replies. I appreciate it.
I did what you suggest literally, and nothing happened.
The command line in cmd just execute the command pdflatex and nothing happened. No pdf is generated. 
Just a new command line appeared.
I am looking forward to hearing from you
thanks again for your help.
Yours sincerely,

**Comment by BoxiLi** [comment]
Usually, the command `pdflatex` will leave some log files in the current directory. Did you see any new file? Like `qcircuit_example.log` or `qcircuit_example.aux`.

If you don't see anything, then there is probably still something wrong with MikTeX.

**Comment by FarooqKhaleel** [comment]
I opened the windows command window as admin and run the above script.
Just a new line appears and no log file is generated at the Desktop.
:((

**Comment by BoxiLi** [comment]
What about executing it not as an admin?

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/122919789-5077fe00-d369-11eb-8485-17232a5372ba.JPG)
Just a new line appears.
I run it as not admin.

**Comment by BoxiLi** [comment]
Ok... Nothing appears, could you try `where pdflatex` and check if the returned path is the MikTeX one?

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/122920372-017e9880-d36a-11eb-9733-e5a3a2ef1531.JPG)

**Comment by BoxiLi** [comment]
Ha, you have two `pdflatex` installed somehow.

Try to use `pip uninstall pdflatex` to remove that python one. And check if only the MiKTeX one remains with `where pdflatex`. 

Then restart cmd and see if `pdflatex qcircuit_example.tex` gives you something reasonable.

**Comment by BoxiLi** [comment]
Or `pip uninstall latextools`, `pip uninstall Latex`, if that `pdflatex` comes with them.

Just remove everything in `pip` regarding `latex`.

**Comment by FarooqKhaleel** [comment]
I did it but a lot of things happening when i run the command pdflatex example.tex, I will be back as soon as possible.

**Comment by BoxiLi** [comment]
> a lot of things happening when i run the command pdflatex example.tex

Don't panic. That is as expected.

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/122921938-c715fb00-d36b-11eb-9a44-610ed8237834.JPG)

**Comment by FarooqKhaleel** [comment]
The pdf file is generated and the circuit is drawn perfectly. Now i return to python?

**Comment by BoxiLi** [comment]
> Now i return to python?

Yep

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/122922568-6e932d80-d36c-11eb-9606-3b55d3ecfaa8.JPG)

**Comment by FarooqKhaleel** [comment]
The drawing does not appear. Just a new line appears.

**Comment by BoxiLi** [comment]
Cool, there is no error message, which means that we are likely to have succeeded.

The figure will only be rendered properly in a Jupyter Notebook. Just as the link you gave: https://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/examples/quantum-gates.ipynb#Gates-in-QuTiP-and-their-representation

You can now install a Jupyter notebook by
`pip install jupyter notebook`

and then use `jupyter notebook` in cmd to start it. It will be opened in your default browser.

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/122923375-52dc5700-d36d-11eb-9e03-de4ff7f26eb9.JPG)

**Comment by BoxiLi** [comment]
Okay, it seems that you already installed `jupyter notebook` but it is not in the system path, could you try `python -m notebook`?

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/122924237-3987da80-d36e-11eb-8ef6-b6e7bd5da77c.JPG)

**Comment by BoxiLi** [comment]
It could also be `python -m notebook`, `py -m notebook` depending on your system.

**Comment by FarooqKhaleel** [comment]
by applying
python -m notebook

It opened in the browser, but there too many file. how can i find the picture?

**Comment by BoxiLi** [comment]
It will open in the current directory. if you change the directory in cmd before calling the notebook, it will also change.

You need to create a new Jupyter Notebook by clicking the `new` button,
![image](https://user-images.githubusercontent.com/12125783/122925270-f6763900-d366-11eb-8f13-c68713460598.png)

Copy your code there and run it.

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/122925543-9afc7900-d36f-11eb-887a-269902025a1f.JPG)

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/122925737-cbdcae00-d36f-11eb-9fc1-f01d03e58aa8.JPG)

**Comment by FarooqKhaleel** [comment]
Finally, you are a legend.
Thank you very much for your time and efforts.
I appreciate it and i wish you all the best.

**Comment by BoxiLi** [comment]
That's it. Bravo!

**Comment by FarooqKhaleel** [comment]
@BoxiLi 
Dear Dr. Boxi Li
I hope you are doing well.
Could you please tell me how can i add an input matrix and observe the output matrix independently.
For Example,
If the above circuit is CNOT,
how can i verify the I/O matrices 
INPUT  -- OUTPUT
00 -- 00
01 -- 01
10 -- 11
11 -- 10
Thank you for your help Dr. Boxi.
Yours sincerely,

**Comment by BoxiLi** [comment]
Hi, @FarooqKhaleel, 
the simplest thing is to run `circuit.run(init_state)` for all possible computational basis states.  Checking if the outputs are expected.

PS: I'm no Dr. yet :)

**Comment by FarooqKhaleel** [comment]
@BoxiLi 
Thank you very much for your reply.
I am entering different inputs. However, the dimensions error occurs.
Could you please provide an example?
Thank you very much for your help. I wish you the Ph.D. degree soon with Excellent marks.
Yours sincerely,

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/123456562-a8259c00-d5eb-11eb-8d8a-48d37844e9e1.JPG)

**Comment by FarooqKhaleel** [comment]
@BoxiLi 
I am sorry i am taking your time @BoxiLi .
Should the output be 
1
0
1
0
?
since at the input we have the first bit (at the bottom) is |0> and the first bit (upper one) is |1>?
Thank you very much for your help.
Yours sincerely,

**Comment by purva-thakre** [comment]
> Should the output be
1
0
1
0
?

If you need this output then a `CNOT` gate cannot be applied on your initial state `|00>`. You need to apply a hadamard gate which is labeled as `SNOT` [in the qip module.](https://qutip-qip.readthedocs.io/en/latest/qip-basics.html#gates) . The output of this will also have included normalization constants. 

```python
q.add_gate("SNOT",targets=[0])
```

**Comment by FarooqKhaleel** [comment]
@purva-thakre 
Thank you very much for your time and help.
I need to enter
![Capture](https://user-images.githubusercontent.com/86245057/123467136-d5c51200-d5f8-11eb-8941-42c5655486e1.JPG)

0
1
so the output remains 
0
1
and if i enter
1
0
the output is
1
1
I just want to understand this. so I can build larger circuits.
Thank you very much @purva-thakre 
Yours sincerely,

**Comment by FarooqKhaleel** [comment]
I studies the fundamentals of quantum computations. but I am beginner in qutip. These are my first steps.
Thank you for your help.

**Comment by purva-thakre** [comment]
If you are still starting with a 2 qubit state then your initial state must be changed for the preferred output. 

Instead of `tensor(basis(2,0), basis(2,0))` change the state to `tensor(basis(2,0), basis(2,0)) + tensor(basis(2,1), basis(2,1))`. Following is the changed `zero_state`. 

```
Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [1.]]
```

```python
q = QubitCircuit(2, reverse_states=False)
q.add_gate("CNOT",controls =[0], targets=[1])
q.png
```
will output following circuit
![image](https://user-images.githubusercontent.com/66048318/123469827-316fab00-d5b9-11eb-92c2-e742413d20f8.png)

```python
initial_state = tensor(basis(2,0), basis(2,0)) + tensor(basis(2,1), basis(2,1))
result = q.run(state=initial_state)
print(result)
```
Result of above is
```
Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [1.]
 [0.]]
```

**Comment by FarooqKhaleel** [comment]
@purva-thakre 
Thank you very much for your detailed answer.
I hope you could explain how the initial state is changed for a single ket on the wire. I mean how may i enter
1
0
to get
1
1
?
Thank you very much for your help.
Yours sincerely,

**Comment by FarooqKhaleel** [comment]
![Capture](https://user-images.githubusercontent.com/86245057/123500430-b5bc3f80-d646-11eb-8d5e-c1a46d4fff34.JPG)
I tried the above, but the dimension is wrong.
why the cnot gate requires 4 input?
I just need 2 inputs.

**Comment by FarooqKhaleel** [comment]
@purva-thakre 
I understood the following
if I enter |10> to the CNOT gate I get the output |11> and it worked perfectly.
Thank you very much for your help and time.
Yours sincerely,

**Comment by luopeis** [comment]
@purva-thakre  Dear Friend I have some questions like @FarooqKhaleel 

![屏幕截图 2023-04-08 202614](https://user-images.githubusercontent.com/128964528/230721079-9421e964-0d15-48e3-9035-f2fc403acab0.png)
I follow  your steps，but  I meet trouble in“ where pfdlatex”，I am sure about I have install the  package of ”pdflatex“，and I have found it in my folder. But the Commend(cmd) reply to me：”Message: The file cannot be found using the provided mode.“
![sada](https://user-images.githubusercontent.com/128964528/230721781-10d62a6f-0be6-4d06-a381-4b4258f7a645.png)
.The chinese means ”Message: The file cannot be found using the provided mode.“

**Comment by luopeis** [comment]
the error is updating
![first](https://user-images.githubusercontent.com/128964528/230753228-29b1c794-4bd5-4a55-9754-ae7560271fc9.png)
![second](https://user-images.githubusercontent.com/128964528/230753232-2de0576d-b721-47b0-b607-dd8723d73d4c.png)
 I have installed the percl.exe ,ImageMagick,and MikTex.
But some new erroe appear.
