### ISSUE TITLE
cannot import name "Gate"

### ISSUE THREAD

**Issue by HumpyBlumpy** [qutip/qutip-qip#93]
Running the first example from the documentation (https://qutip-qip.readthedocs.io/en/latest/qip-basics.html)
```
from qutip_qip.circuit import QubitCircuit
from qutip_qip.operations import Gate
from qutip import tensor, basis

qc = QubitCircuit(N=2, num_cbits=1)
swap_gate = Gate(name="SWAP", targets=[0, 1])

qc.add_gate(swap_gate)
qc.add_measurement("M0", targets=[1], classical_store=0) # measurement gate
qc.add_gate("CNOT", controls=0, targets=1)
qc.add_gate("X", targets=0, classical_controls=[0]) # classically controlled gate
qc.add_gate(swap_gate)

print(qc.gates)
```

gives ` ImportError: cannot import name 'Gate' from 'qutip_qip.operations'`

**Comment by HumpyBlumpy** [comment]
It seems that the many parts of the documentation are wrong/out of date. 
```

U_list = qc.propagators(ignore_measurement=True)
print(U_list)
```
`TypeError: propagators() got an unexpected keyword argument 'ignore_measurement'`

**Comment by purva-thakre** [comment]
@HumpyBlumpy I leave your comment about the documentation being out of date to @BoxiLi. I think there's a disconnect between [`qutip` docs](https://qutip.org/docs/latest/guide/qip/qip-basics.html#gates) and [`qutip-qip` docs](https://qutip-qip.readthedocs.io/en/latest/qip-basics.html) and version of `qutip-qip` installed. 

If you did a non-editable install, the example in `qutip` docs works by importing `Gate` class from `qutip_qip.circuit` and using just `qc.propagators()` without the argument.

**Comment by HumpyBlumpy** [comment]
@purva-thakre I followed the installation instructions from the same page https://qutip-qip.readthedocs.io/en/latest/installation.html.
Namely, I just did `pip install qutip-qip`. Was I supposed to do something else? Or should I be using the qip module from qutip, i.e qutip.qip?

**Comment by purva-thakre** [comment]
> Or should I be using the qip module from qutip, i.e qutip.qip?

@HumpyBlumpy  No, you should be using `qutip_qip`. My comment was with regards to making some small changes to get your code working until someone else who has a better idea of the version installed via `pip` installation adds their comment. 

```python
from qutip_qip.circuit import QubitCircuit, Gate
from qutip import tensor, basis

qc = QubitCircuit(N=2, num_cbits=1)
swap_gate = Gate(name="SWAP", targets=[0, 1])

qc.add_gate(swap_gate)
qc.add_measurement("M0", targets=[1], classical_store=0) # measurement gate
qc.add_gate("CNOT", controls=0, targets=1)
qc.add_gate("X", targets=0, classical_controls=[0]) # classically controlled gate
qc.add_gate(swap_gate)

print(qc.gates)
```

```python
U_list = qc.propagators()
print(U_list)
```

**Comment by BoxiLi** [comment]
@HumpyBlumpy Thanks for the issue. There are two versions of `qutip-qip` and the doc, `stable` and `latest`. You can see it at the left bottom part of the RTD doc.
![image](https://user-images.githubusercontent.com/12125783/132635745-2ded7d84-a541-4dc5-88d1-7c8f982eb918.png)

If you are using the version downloaded through `pip`. You are using the released version, and this needs to be changed to `stable`. The `latest` is the version of the master branch.  You need to download the code and install it from the source. In the master branch, things are not very stable and may be subject to change. 

We should add a note at the beginning saying that this is not the stable version.

**Comment by BoxiLi** [comment]
I have updated the link in the README etc so that they all direct to the stable version. Thanks for pointing this out.

**Comment by HumpyBlumpy** [comment]
Thanks!
